import assert from 'node:assert/strict';
export async function testLiveBuildSource(db, base, source) {
  await db.exec(`create schema auth;create table auth.users(id uuid primary key);
    create role anon;create role authenticated;create role service_role bypassrls;
    grant usage on schema auth,public to service_role,anon,authenticated;
    grant select,update on auth.users to service_role;`);
  await db.exec(base);await db.exec(source);
  const owner='11111111-1111-4111-8111-111111111111',friend='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333';
  await db.query('insert into auth.users values($1),($2),($3)',[owner,friend,other]);await db.exec('set role service_role');
  const rpc=async(fn,actor,action,input)=>(await db.query(`select public.${fn}($1,$2,$3::jsonb) result`,[actor,action,JSON.stringify(input)])).rows[0].result;
  const control=(a,b,c)=>rpc('companion_live_build_control',a,b,c);
  const call=(a,b,c)=>rpc('companion_live_build_source',a,b,c);
  let count=0;const eq=(a,b)=>{assert.deepEqual(a,b);count++;};
  const deny=async(f,code)=>{await assert.rejects(f,e=>e.code===code);count++;};
  let group=await control(owner,'create',{source_sha256:'a'.repeat(64),grid_wide:2,grid_tall:1,consent:true});
  const id={build_id:group.id};
  group=await control(owner,'invite',{...id,expected_revision:group.revision,invite_hash:'b'.repeat(64)});
  group=await control(friend,'join',{invite_hash:'b'.repeat(64),consent:true});
  const manifest={...id,kind:'two_layer_zip',size_bytes:2097153,part_sha256:['c'.repeat(64),'d'.repeat(64)],consent:true};
  await deny(()=>call(friend,'source_begin',manifest),'42501');
  await deny(()=>call(owner,'source_begin',{...manifest,consent:false}),'22023');
  await deny(()=>call(owner,'source_begin',{...manifest,part_sha256:[null,null]}),'22023');
  await deny(()=>call(owner,'source_begin',{...manifest,part_sha256:['c'.repeat(64)]}),'22023');
  eq((await call(owner,'source_begin',manifest)).ready,false);
  eq((await call(owner,'source_begin',manifest)).ready,false);
  await deny(()=>call(owner,'source_begin',{...manifest,size_bytes:2097154}),'40001');
  eq((await call(friend,'source_read',id)).available,false);
  eq((await call(friend,'source_part_read',{...id,part:0})).available,false);
  await deny(()=>call(other,'source_read',id),'42501');
  await deny(()=>call(friend,'source_commit',id),'42501');
  eq((await call(owner,'source_part_write',{...id,part:1})).size_bytes,1);
  await deny(()=>call(owner,'source_part_write',{...id,part:2}),'22023');
  eq((await call(owner,'source_commit',id)).ready,true);
  eq((await call(friend,'source_read',id)).source_sha256,'a'.repeat(64));
  eq((await call(friend,'source_part_read',{...id,part:0})).size_bytes,2097152);
  await deny(()=>call(owner,'source_part_write',{...id,part:0}),'40001');
  group=await control(owner,'remove_member',{...id,expected_revision:group.revision,member_id:friend});
  await deny(()=>call(friend,'source_part_read',{...id,part:0}),'42501');
  await control(owner,'close',{...id,expected_revision:group.revision});
  await deny(()=>call(owner,'source_read',id),'42501');
  await db.exec('set role authenticated');
  await deny(()=>db.query('select * from public.companion_live_build_sources'),'42501');
  await deny(()=>call(owner,'source_read',id),'42501');
  return count;
}
