project_id = "mapart"

[functions.companion-api]
verify_jwt = true

[functions.companion-auth]
verify_jwt = false

[functions.companion-device]
verify_jwt = false

[functions.companion-mod]
verify_jwt = false

[functions.companion-lens]
verify_jwt = false

[functions.companion-telemetry]
verify_jwt = false

[functions.companion-export-archive]
enabled = true
verify_jwt = false
import_map = "./functions/companion-export-archive/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/companion-export-archive/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/companion-export-archive/*.html" ]
