import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CheckCircledIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CircleIcon,
  CopyIcon,
  Cross2Icon,
  DotFilledIcon,
  EyeClosedIcon,
  EyeOpenIcon,
  Half2Icon,
  LockClosedIcon,
  LockOpen1Icon,
  MinusIcon,
  PlusIcon,
} from '@radix-ui/react-icons';
import {
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconAnchor,
  IconArchive,
  IconArrowBackUp,
  IconArrowForwardUp,
  IconArrowsExchange2,
  IconArrowsMove,
  IconArtboard,
  IconBook2,
  IconBrush,
  IconBucket,
  IconCloud,
  IconColorPicker,
  IconColorSwatch,
  IconColumns2,
  IconCrop,
  IconDeviceFloppy,
  IconDownload,
  IconEraser,
  IconFileDescription,
  IconFolderOpen,
  IconGrid4x4,
  IconGridDots,
  IconHammer,
  IconHelpHexagon,
  IconKeyboard,
  IconLasso,
  IconLayersIntersect,
  IconLetterT,
  IconLayoutAlignCenter,
  IconLink,
  IconListCheck,
  IconLogin2,
  IconMap,
  IconPackage,
  IconPaint,
  IconPalette,
  IconPhoto,
  IconPhotoDown,
  IconPick,
  IconPlayerPause,
  IconPlayerPlay,
  IconPointer,
  IconRefresh,
  IconSelect,
  IconSettings,
  IconShare3,
  IconStack2,
  IconTrash,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconWand,
  IconZoomReset,
} from '@tabler/icons-react';
import { ColorsSwatch } from 'pixelarticons/react/ColorsSwatch';
import { Download } from 'pixelarticons/react/Download';
import { Folder } from 'pixelarticons/react/Folder';
import { Heart } from 'pixelarticons/react/Heart';
import { ImageNew } from 'pixelarticons/react/ImageNew';
import { Play } from 'pixelarticons/react/Play';
import { Save } from 'pixelarticons/react/Save';
import { Settings2 } from 'pixelarticons/react/Settings2';
import { Upload } from 'pixelarticons/react/Upload';
import type { MkIcon, MkIconDefinition } from './IconGlyph';

const radix = (component: MkIcon): MkIconDefinition => ({ component, family: 'radix', defaultSize: 15 });
const tabler = (component: MkIcon): MkIconDefinition => ({ component, family: 'tabler', defaultSize: 18 });
const pixel = (component: MkIcon): MkIconDefinition => ({ component, family: 'pixel', defaultSize: 24 });

/**
 * MapKluss icon language:
 * - Radix: dense micro-controls and state glyphs at their native 15 px grid.
 * - Tabler: editor, cloud, palette and export actions on a 24 px / 2 px-stroke grid.
 * - Pixelarticons: game-native global actions and large mobile/empty-state accents.
 */
export const mkIcons = {
  // Radix micro-controls
  arrowDown: radix(ArrowDownIcon),
  arrowLeft: radix(ArrowLeftIcon),
  arrowRight: radix(ArrowRightIcon),
  arrowUp: radix(ArrowUpIcon),
  check: radix(CheckIcon),
  checkCircle: radix(CheckCircledIcon),
  chevronDown: radix(ChevronDownIcon),
  chevronLeft: radix(ChevronLeftIcon),
  chevronRight: radix(ChevronRightIcon),
  circle: radix(CircleIcon),
  circleFilled: radix(DotFilledIcon),
  circleHalf: radix(Half2Icon),
  close: radix(Cross2Icon),
  copy: radix(CopyIcon),
  eye: radix(EyeOpenIcon),
  eyeOff: radix(EyeClosedIcon),
  lock: radix(LockClosedIcon),
  unlock: radix(LockOpen1Icon),
  minus: radix(MinusIcon),
  plus: radix(PlusIcon),
  // Tabler editor and application actions
  adjustments: tabler(IconAdjustmentsHorizontal),
  alert: tabler(IconAlertTriangle),
  alignCenter: tabler(IconAlignCenter),
  alignLeft: tabler(IconAlignLeft),
  alignRight: tabler(IconAlignRight),
  anchor: tabler(IconAnchor),
  archive: tabler(IconArchive),
  artist: tabler(IconPaint),
  blockTextures: tabler(IconPackage),
  brush: tabler(IconBrush),
  cloud: tabler(IconCloud),
  compare: tabler(IconColumns2),
  crop: tabler(IconCrop),
  deselect: tabler(IconLayersIntersect),
  eraser: tabler(IconEraser),
  export: tabler(IconDownload),
  exportImage: tabler(IconPhotoDown),
  file: tabler(IconFileDescription),
  fill: tabler(IconBucket),
  gradient: tabler(IconColorSwatch),
  grid: tabler(IconGrid4x4),
  guide: tabler(IconHelpHexagon),
  import: tabler(IconUpload),
  invert: tabler(IconArrowsExchange2),
  keyboard: tabler(IconKeyboard),
  lasso: tabler(IconLasso),
  layer: tabler(IconStack2),
  layoutCenter: tabler(IconLayoutAlignCenter),
  link: tabler(IconLink),
  login: tabler(IconLogin2),
  map: tabler(IconMap),
  move: tabler(IconArrowsMove),
  package: tabler(IconPackage),
  paletteEditor: tabler(IconPalette),
  pattern: tabler(IconGridDots),
  pause: tabler(IconPlayerPause),
  pickaxe: tabler(IconPick),
  projectEditor: tabler(IconFolderOpen),
  redo: tabler(IconArrowForwardUp),
  reset: tabler(IconRefresh),
  saveEditor: tabler(IconDeviceFloppy),
  select: tabler(IconPointer),
  selectRect: tabler(IconSelect),
  settings: tabler(IconSettings),
  share: tabler(IconShare3),
  text: tabler(IconLetterT),
  tourAdvanced: tabler(IconPlayerPlay),
  tracker: tabler(IconListCheck),
  trash: tabler(IconTrash),
  undo: tabler(IconArrowBackUp),
  uploadEditor: tabler(IconUpload),
  user: tabler(IconUser),
  userCheck: tabler(IconUserCheck),
  view: tabler(IconPhoto),
  wand: tabler(IconWand),
  wiki: tabler(IconBook2),
  zoomReset: tabler(IconZoomReset),
  eyedropper: tabler(IconColorPicker),
  artboard: tabler(IconArtboard),
  hammer: tabler(IconHammer),

  // Pixelarticons brand and game-native accents
  download: pixel(Download),
  newCanvas: pixel(ImageNew),
  palette: pixel(ColorsSwatch),
  play: pixel(Play),
  project: pixel(Folder),
  save: pixel(Save),
  sliders: pixel(Settings2),
  support: pixel(Heart),
  upload: pixel(Upload),
} satisfies Record<string, MkIconDefinition>;
